### ISSUE TITLE
about layer.py

### ISSUE THREAD

**Issue by the-starry-sea** [biomed-AI/CoSMIG#2]
hi author:

> When I read this article, I thought it was a wonderful paper. I ran the code of this paper and reproduced the results on transductive scenario . Then I spent much time reading and understanding the code but when I read the code of _layer.py_, I was puzzled that the code and the written of paper were completely out of line. At first, I thought I didn't understand it until I found the code exactly the same as [pytorch geometric](https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/nn/conv/rgcn_conv.py) on GitHub,  you use the code of his model to run out the results of your paper????????? 

> Is your model effective?

**Comment by Jh-SYSU** [comment]
Thanks for your reading.

The difference of Our Code and RGCN-PyG is the use of edge-attr in message passing.

For example, line 221 in layer.py:
```
row, col = edge_index
new_edge_attr = self.mlp(torch.cat([out[row], out[col], edge_attr], dim=-1))
```
It is the message passing form node to edge, which corresponding the Equation (7)

Similar for node embedding updating:
```
h = self.propagate(tmp, x=x_l, edge_attr=edge_attr_tmp, size=size)
```

In fact, we have two version of our code and the public code uses the PyG framework for the convenience of everyone to read.
You can refer to another version of the code from https://github.com/SY575/CMPNN, which is also our paper, also using the Communicative mechanism
